name: vscreen
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - rdkit>=2023.03
  - pandas>=1.5
  - numpy>=1.23
  - scikit-learn>=1.2
  - joblib>=1.2
  - pyyaml>=6.0
  - matplotlib>=3.6
  - scipy>=1.10
  - openbabel>=3.1
  - autodock-vina>=1.2
  - fpocket>=4.0
  - pip:
    - meeko>=0.5
